# Allure Report Configuration
allure.results.directory=${allure.results.directory}
allure.link.issue.pattern=${allure.link.issue}{}
allure.link.tms.pattern=${allure.link.tms}{}
allure.labels.owner=${allure.owner}
allure.labels.severity.critical=Critical
allure.labels.severity.normal=Normal
allure.labels.severity.minor=Minor